name: PrimeRewardsApprover
main: su.primecorp.primerewards.PrimeRewardsApproverPlugin
version: 1.0.0
api-version: '1.21'
authors: [PRIMECORP]
website: https://primecorp.su
description: Выдача покупок по режимам, наград за голосования и подписки через MySQL.
permissions:
  primerewards.reload:
    default: op
commands:
  primerewards:
    description: Управление PrimeRewardsApprover
    usage: /<command> reload|stats
    aliases: [prewards, rewardsapprover]
